[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
cursor = "0x4d4d4c"
text = "0xffffff"

[colors.primary]
background = "0x00131d"
foreground = "0x7e9aa6"

[font]
size = 10

[font.bold]
family = "Hack"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Light"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.7

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
